ARG migrate_version
FROM migrate/migrate:${migrate_version}

COPY --chown=root:root ./dockerfiles/migrate.sh /migrate.sh
COPY --chown=root:root ./migrations/* /migrations/

ENTRYPOINT ["/migrate.sh"]
