ARG migrate_version
FROM migrate/migrate:${migrate_version:-v4.17.1}

COPY --chown=root:root ./dockerfiles/migrate.sh /migrate.sh
COPY --chown=root:root ./data/postgres/migrations/* /migrations/

ENTRYPOINT ["/migrate.sh"]
