name: Build

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH access to private repos
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.CI_SSH_PRIVATE_KEY }}"
        ssh-add -l

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test

    - name: Cleanup SSH
      run: |
        ssh-add -D
